login/config/routes.rb
Rails.application.routes.draw do
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/logout' , to:'sessions#new'
  resources :users

  get  '/newsurvey', to: 'surveys#new'
  post '/newsurvey',  to: 'surveys#create'
  resources :surveys
  
  get  '/newquestions', to: 'questions#new'
  post '/newquestions',  to: 'questions#create'
  resources :questions

  get  '/newoptions', to: 'options#new'
  post '/newoptions',  to: 'options#create'
  resources :options
 
  get '/references/new', to: 'references#new'
  resources :references

  get '/active_surveys', to: 'links#show'
  resources :links

  root 'users#new'

end

login/app/models/user.rb
class User < ActiveRecord::Base
	has_many :links
	before_save { self.email = email.downcase }
	validates :first_name, presence: true, length: {maximum: 50}
	validates :last_name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255}, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
			BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end
end

login/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
	before_action :admin_user, only: [:destroy,  :update]
	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def index
		@users = User.all
	end
	
	def create
		@user = User.new(user_params)
		if @user.save
			log_in @user
			flash[:success] = "Welcome to the Sample App!"
			redirect_to @user
		else
			render "new"
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated"
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User deleted"
		redirect_to users_url
	end

	private

	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password,:password_confirmation ,:image)
	end

	def logged_in_user
		unless logged_in?
			flash[:danger] = "Please log in."
			redirect_to login_url
		end
	end

	def correct_user
		@user = User.find(params[:id])
		render 'show' unless current_user?(@user)
	end

	def admin_user
		redirect_to(root_url) unless current_user.admin?
	end
end

login/app/helpers/users_helper.rb
module UsersHelper
end

login/app/views/users/_user.html.erb
<li>
<%= link_to user.first_name, user %>
<% if current_user.admin? && !current_user?(user) %>
	| <%= link_to "delete", user, method: :delete,
		data: { confirm: "You sure?" } %>
<% end %>
</li>

login/app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<h1>Let's Survey</h1>
		</div>
		<div class="col-md-9">
		</div>
	</div>
</nav>

<div class="row">
<div class="col-md-6 col-md-offset-3">
	<h1> Update your profile</h1>
	<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages' %>

		<%= f.label :first_name %><br>
		<%= f.text_field :first_name, class: 'form-control' %>
		<br>
		<%= f.label :last_name %><br>
		<%= f.text_field :last_name, class: 'form-control' %>
		<br>

		<%= f.label :email %><br>
		<%= f.email_field :email, class: 'form-control' %>
		<br>
		<%= f.label :password %><br>
		<%= f.password_field :password, class: 'form-control' %>
		<br>
		<%= f.label :password_confirmation, "Confirmation" %><br>
		<%= f.password_field :password_confirmation, class: 'form-control' %>
		<br>
		<%= f.submit :"Save changes", class: "btn btn-primary" %>
	<% end %>

	</div>
</div>

login/app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<h1>Let's Survey</h1>
		</div>
		<div class="col-md-9">
		</div>
	</div>
</nav>
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1> All users</h1>

		<ul class="users">
			<table class="table">
				<thead>
					<tr>
						<th>First Name</th>
						<th>Delete</th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
						<% if current_user.admin? && !current_user?(user) %>
								<tr class="info">
									<td>
										<%= link_to user.first_name, edit_user_path(user)%>
									</td>
									<td>
										<%= link_to "delete", user, method: :delete,
											data: { confirm: "You sure?" } %>
								</td>
								</tr>
						<% end %>
			<% end %>
		</tbody>
			</table>
		</ul>
	</div>
</div>

login/app/views/users/new.html.erb
<% provide(:title,'Sign up') %>
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<h1>Let's Survey</h1>
		</div>
		<div class="col-md-9">
		</div>
		<ul class="nav navbar-nav">
			<li>
				<h3>			
					<li><%= link_to "Log in", login_path %></li>
				</h3>	
			</li>
		</ul>
	</div>
</nav>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1> Sign Up </h1>
		<%= form_for(@user, url: signup_path) do |f| %>
			<%= render 'shared/error_messages' %>
			<%= f.label :first_name %><br>
			<%= f.text_field :first_name, class: 'form-control' %>
			<br>
			<%= f.label :last_name %><br>
			<%= f.text_field :last_name, class: 'form-control' %>
			<br>
			<%= f.label :email %><br>
			<%= f.email_field :email, class: 'form-control' %>
			<br>

			<%= f.label :password %><br>
			<%= f.password_field :password, class: 'form-control' %>
			<br>
			<%= f.label :password_confirmation, "Confirmation" %><br>
			<%= f.password_field :password_confirmation, class: 'form-control' %>
			<br>
			<%= f.submit "Create my account", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

login/app/views/users/show.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<h1>Let's Survey</h1>
		</div>
		<ul class="nav navabr-nav col-md-6 col-md-offset-3" >
			<h3>
			<% if (current_user).admin? %> 
				<%= link_to "Users", users_path %>
			<% end %>
			&nbsp
			&nbsp
			<% if logged_in? %>
					<%= link_to "Logout", logout_path, method: "delete" %>
			&nbsp
			&nbsp
					<%= link_to "Settings", edit_user_path(current_user) %>
			&nbsp
			&nbsp
			<% else %>
					<%= link_to "Log in", login_path %>
			&nbsp
			&nbsp
			<% end %>
			</h3>
		</ul>
	</div>
	</div>
</nav>
<div class="row">
	<div class="col-md-6 col-md-offset-3">

<table class="table">
<tbody>
<% if (current_user).admin? %>

	<tr class="info">
		<td>
			<%= link_to "Add Survey" , '/newsurvey' %>
			</td>
		</tr>

		<tr class="info">
		<td>
		<%= link_to "Add Question" , '/newquestions' %>
			</td>
		</tr>
		<tr class="info">
		<td>
		<%= link_to "Add Options" , '/newoptions' %>
			</td>
		</tr>
		<tr class="info">
		<td>
		<%= link_to "View Response" , '/references' %>
			</td>
		</tr>
<% end %>
<tr class="info">
	<td>
		<%= link_to "See All The Surveys" , '/surveys' %>
		</td>
		</tr>
</tbody>
</table>
	</div
</div>