login/config/routes.rb
Rails.application.routes.draw do
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/logout' , to:'sessions#new'
  resources :users

  get  '/newsurvey', to: 'surveys#new'
  post '/newsurvey',  to: 'surveys#create'
  resources :surveys
  
  get  '/newquestions', to: 'questions#new'
  post '/newquestions',  to: 'questions#create'
  resources :questions

  get  '/newoptions', to: 'options#new'
  post '/newoptions',  to: 'options#create'
  resources :options
 
  get '/references/new', to: 'references#new'
  resources :references

  get '/active_surveys', to: 'links#show'
  resources :links

  root 'users#new'

end

login/app/models/survey.rb
class Survey < ActiveRecord::Base
	has_many :questions , dependent: :destroy
	has_many :options , dependent: :destroy
	has_many :links
	validates :name, presence: true, length: {maximum: 255}, uniqueness: { case_sensitive: false }
end

login/app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
	def new
		@survey=Survey.new
	end
	
	def index
		@surveys = Survey.all
	end

	def create
		@survey = Survey.new(survey_params)
		if @survey.save
			flash[:success] = "Survey Created!"
			redirect_to current_user
		else
			redirect_to '/newsurvey'
		end
	end
	
	def show
		@survey = Survey.find(params[:id])
		@questions = Question.where(survey_id: @survey.id)
	end


	def edit
		@survey = Survey.find(params[:id])
	end

	def update
		@survey = Survey.find(params[:id])
		if @survey.update_attributes(survey_params)
			flash[:success] = "Survey updated"
			redirect_to current_user
		else
			render 'edit'
		end
	end

	def destroy
		Survey.find(params[:id]).destroy
		flash[:success] = "Survey deleted"
		redirect_to current_user
	end

	private
		def survey_params
			params.require(:survey).permit(:name)
		end
end

login/app/helpers/surveys_helper.rb
module SurveysHelper
end

login/app/views/surveys/edit.html.erb
<% provide(:title, "edit survey") %>
<h1> update your survey</h1>
<div class="row">
<div class="col-md-6 col-md-offset-3">
	<%= form_for(@survey) do |f| %>
		<%= render 'shared/error_messages_1' %>

		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>
		
		<%= f.submit "save changes", class: "btn btn-primary" %>
	<% end %>

	</div>
</div>

login/app/views/surveys/index.html.erb
<% provide(:title, 'All Surveys') %>
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<h1>Let's Survey</h1>
		</div>
		<div class="col-md-9">
		</div>
	</div>
</nav>
<div class="row">
	<div class="col-md-6 col-md-offset-3">

<h1> All Surveys</h1>

<ul class="users">
		<table class="table">
		<thead>
			<tr>
				<th>Survey</th>
			</tr>
		</thead>
		<tbody>

			<% @surveys.each do |survey| %>
				<tr class="info">
					<td>
						<%= link_to survey.name, survey %>
					</td>
			<% if current_user.admin?%>
				<td>
				<%= link_to "edit", edit_survey_path(survey)%>
				</td>
				<td>
				 <%= link_to "delete", survey, method: :delete,
					 data: { confirm: "You sure?" } %>
			</td>
			<%end%>
				</tr>
			<% end %>
		</tbody>
		</table>
</ul>
	</div>
</div>

login/app/views/surveys/new.html.erb
<% provide(:title,'Sign up') %>
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<h1>Let's Survey</h1>
		</div>
	</div>  
</nav>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1> Create Survey </h1>
		<%= form_for(@survey) do |f| %>
			<%= render 'shared/error_messages_1' %>
			<%= f.label :survey_name %><br>
			<%= f.text_field :name, class: 'form-control' %>
			<br>
			<%= f.submit "Create Survey", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

login/app/views/surveys/show.html.erb
<% provide(:title, 'All Questions') %>
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<h1>Let's Survey</h1>
		</div>
		<div class="col-md-9">
		</div>
	</div>
</nav>
<div class="row">
	<div class="col-md-6 col-md-offset-3">

<h1> All Questions to the Survey</h1>

<ul class="users">
		<table class="table">
		<thead>
			<tr>
				<th>Question</th>
			</tr>
		</thead>
		<tbody>
			<% @questions.each do |question| %>
				<tr class="info">
			<% if current_user.admin?%>
				<td>	<%= link_to question.q_name, question_path(question.id) %>
			</td><td><%= link_to "edit", edit_question_path(question)%>
		</td><td> <%= link_to "delete", question, method: :delete,
			data: { confirm: "You sure?" } %></td>
			<% end %>
			<% if !current_user.admin? %>
				<td>
					<%= link_to question.q_name, new_reference_path('type'=>question.id) %>
				</td>
			<% end %>
				</tr>
	<% end %>
		</tbody>
		</table>
</ul>
	</div>
</div>