login/config/routes.rb
Rails.application.routes.draw do
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/logout' , to:'sessions#new'
  resources :users

  get  '/newsurvey', to: 'surveys#new'
  post '/newsurvey',  to: 'surveys#create'
  resources :surveys
  
  get  '/newquestions', to: 'questions#new'
  post '/newquestions',  to: 'questions#create'
  resources :questions

  get  '/newoptions', to: 'options#new'
  post '/newoptions',  to: 'options#create'
  resources :options
 
  get '/references/new', to: 'references#new'
  resources :references

  get '/active_surveys', to: 'links#show'
  resources :links

  root 'users#new'

end

login/app/models/question.rb
class Question < ActiveRecord::Base
	has_many :options , dependent: :destroy
	belongs_to :survey
	validates :q_name, presence: true, length: {maximum: 1000}, uniqueness: { case_sensitive: false }
end

login/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def new
		@question=Question.new
	end
	
	def create
		@question = Question.new(question_params)
		if @question.save
			flash[:success] = "Question Created!"
			redirect_to current_user
		else
			redirect_to '/newquestions'
		end
	end
	
	def show
		@question = Question.find(params[:id])
		@options = Option.where(question_id: @question.id)
	end

	def edit
		@question = Question.find(params[:id])
	end

	def update
		@question = Question.find(params[:id])
		if @question.update_attributes(question_params)
			flash[:success] = "Question updated"
			redirect_to current_user
		else
			render 'edit'
		end
	end

	def destroy
		Question.find(params[:id]).destroy
		flash[:success] = "Question deleted"
		redirect_to current_user
	end

	private
		def question_params
			params.require(:question).permit(:q_name, :survey_id, :q_definition)
		end

end

login/app/helpers/questions_helper.rb
module QuestionsHelper
end

login/app/views/questions/edit.html.erb
<% provide(:title, "edit questions") %>
<h1> update your questions</h1>
<div class="row">
<div class="col-md-6 col-md-offset-3">
	<%= form_for(@question) do |f| %>
		<%= render 'shared/error_messages_2' %>

		<%= f.label :name %><br>
		<%= f.text_field :q_name, class: 'form-control' %>
		<br>
		<%= f.label :name %><br>
		<%= f.text_field :q_name, class: 'form-control' %>
		<br>
		<%= f.label :"type" %><br>
		<%= f.select :q_definition, ['single-correct-objective','multiple-corret-objective','subjective'] , class: 'form-control' %>
		<br>
		<%= f.submit "save changes", class: "btn btn-primary" %>
	<% end %>

	</div>
</div>

login/app/views/questions/new.html.erb
<% provide(:title,'Questions') %>
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<h1>Let's Survey</h1>
		</div>
	</div>  
</nav>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1> Create Questions </h1>
		<%= form_for(@question) do |i| %>
		<%= render 'shared/error_messages_2' %>
			<%= i.label :"question" %><br>
			<%= i.text_field :q_name, class: 'form-control' %>
			<br>
			<%= i.label :"survey_name" %><br>
			<%= i.select :survey_id, options_for_select(Survey.all.map {|p| [p.name , p.id]}) , class: 'form-control'%>
			<br>
			<br>
			<%= i.label :"type" %><br>
			<%= i.select :q_definition, ['single-correct-objective','multiple-corret-objective','subjective'] , class: 'form-control' %>
			<br>
			<br>
			<%= i.submit "Add question", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

login/app/views/questions/show.html.erb
<% provide(:title, 'All Surveys') %>
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<h1>Let's Survey</h1>
		</div>
		<div class="col-md-9">
		</div>
	</div>
</nav>
<div class="row">
	<div class="col-md-6 col-md-offset-3">


<h1> All Options to the Question</h1>

<ul class="users">
		<table class="table">
		<thead>
			<tr>
				<th>Option</th>
			</tr>
		</thead>
		<tbody>

			<% @options.each do |option| %>
				<tr class="info">
					<td>
						<%= option.q_option %>
					</td>
					<% if current_user.admin?%>
						<td>
						<%= link_to "edit", edit_option_path(option)%>
						</td>
						<td>
				<%= link_to "delete", option, method: :delete,
					data: { confirm: "You sure?" } %>
					</td>
			<% end %>
				</tr>
	<% end %>
		</tbody>
		</table>
</ul>
	</div>
</div>